pull_request_rules:          
    - name: Automatically Dependenabot bot's PRs
      conditions:
      - author=dependabot[bot]
      - "check-success = Build NanoFramework SLN (Release)"
      - "#commits-behind = 0"
      actions:
        merge:
          method: merge
          commit_message_template: |
            Automerge from {{ head }}
            
            {{ title }} (#{{ number }})
            
            {{ body }}
        label:
          toggle:
             - cleanup
             - automated

    - name: Automatically Nanodu Dependenabot bot's PRs
      conditions:
      - author=TekuSP
      - "head ~=nfbot/update-dependencies/"
      - "check-success = Build NanoFramework SLN (Release)"
      - "#commits-behind = 0"
      actions:
        merge:
          method: merge
          commit_message_template: |
            Automerge from {{ head }}
            
            {{ title }} (#{{ number }})
            
            {{ body }}
        label:
          toggle:
             - cleanup
             - automated
             
    - name: Automatically Changelog PRs
      conditions:
      - author=TekuSP
      - "head ~=update-changelog"
      - "check-success = Build NanoFramework SLN (Release)"
      - "#commits-behind = 0"
      actions:
        merge:
          method: merge
          commit_message_template: |
            Automerge from {{ head }}
            
            {{ title }} (#{{ number }})
            
            {{ body }}
        label:
          toggle:
             - cleanup
             - automated
             
    - name: Automatically approve Changelog PRs
      conditions:
      - author=TekuSP
      - "head ~=update-changelog"
      - "check-success = Build NanoFramework SLN (Release)"
      - "#commits-behind = 0"
      actions:
        review:
          type: APPROVE
        label:
            toggle:
              - approved

    - name: Automatically approve Nanodu Dependenabot bot's PRs
      conditions:
      - author=TekuSP
      - "head ~=nfbot/update-dependencies/"
      - "check-success = Build NanoFramework SLN (Release)"
      - "#commits-behind = 0"
      actions:
        review:
          type: APPROVE
        label:
            toggle:
              - approved
            
    - name: Automatically approve Dependenabot bot's PRs
      conditions:
      - author=dependabot[bot]
      - "check-success = Build NanoFramework SLN (Release)"
      - "#commits-behind = 0"
      actions:
        review:
          type: APPROVE
        label:
            toggle:
              - approved
              
    - name: Automatic update Depenedabot pull requests if they are commits behind
      conditions:
      - author=dependabot[bot]
      - "#commits-behind > 0"
      actions:
         update:

    - name: Automatic update Nanodu Depenedabot pull requests if they are commits behind
      conditions:
      - author=TekuSP
      - "head ~=nfbot/update-dependencies/"
      - "#commits-behind > 0"
      actions:
         update:
    
    - name: Automatic update ChangeRequest pull requests if they are commits behind
      conditions:
      - author=TekuSP
      - "head ~=update-changelog"
      - "#commits-behind > 0"
      actions:
         update:
      
    - name: Ask to resolve conflict
      conditions:
      - conflict
      actions:
        comment:
          message: This pull request is now in conflict. Could you fix it @{{author}}? :)
        label:
            toggle:
              - conflict
          
    - name: Comment when is merged
      conditions:
      - merged
      - "-head ~=update-changelog"
      - "-head ~=nfbot/update-dependencies/"
      - "author!=dependabot[bot]"
      actions:
        comment:
           message: Thank you for your contribution @{{author}}! Your pull request has been merged.
        label:
           toggle:
             - merged
            
    - name: "Assign non Dependabot PR to author: TekuSP"
      conditions:
      - "#files = 1"
      - "author!=dependabot[bot]"
      actions:
        assign:
          add_users:
            - "TekuSP"
        label:
          toggle:
            - "In Review"
            
    - name: Delete head branch after merge if the label "cleanup" is present
      conditions:
        - merged
        - label = cleanup
      actions:
        delete_head_branch:
