//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHalo.Resources
{
    
    internal partial class IconResources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((IconResources.manager == null))
                {
                    IconResources.manager = new System.Resources.ResourceManager("OpenHalo.Resources.IconResources", typeof(IconResources).Assembly);
                }
                return IconResources.manager;
            }
        }
        internal static nanoFramework.UI.Bitmap GetBitmap(IconResources.BitmapResources id)
        {
            return ((nanoFramework.UI.Bitmap)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            settings = -20938,
        }
    }
}
