//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHalo.Resources
{
    
    internal partial class SetupWebpageResources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((SetupWebpageResources.manager == null))
                {
                    SetupWebpageResources.manager = new System.Resources.ResourceManager("OpenHalo.Resources.SetupWebpageResources", typeof(SetupWebpageResources).Assembly);
                }
                return SetupWebpageResources.manager;
            }
        }
    }
}
