# Copyright (c) .NET Foundation and Contributors
# https://github.com/networkfusion/MBN-TinyCLR/ original build
name: Daily update dependencies

on: 
  schedule:
  # At 00:00 UTC every day.
  - cron:  '0 0 * * *'
  repository_dispatch:
    types: update-dependencies

defaults:
  run:
    shell: pwsh

jobs:
  dependencies-update:
    name: Update .NET nanoFramework dependencies
    timeout-minutes: 15
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: nanoframework/nanodu@v1.0.23
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          previewPackages: false
          solutionsToCheck: OpenHalo.sln
