# Copyright (c) .NET Foundation and Contributors
# https://github.com/networkfusion/MBN-TinyCLR/ original build
name: Daily update dependencies

on: 
  schedule:
  # At 00:00 UTC every day.
  - cron:  '0 0 * * *'
  repository_dispatch:
    types: update-dependencies

defaults:
  run:
    shell: pwsh

jobs:
  dependencies-update:
    name: Update .NET nanoFramework dependencies
    timeout-minutes: 15
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Install NuGet client
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - uses: nanoframework/nanodu@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          previewPackages: false
