# Copyright (c) .NET Foundation and Contributors
# https://github.com/networkfusion/MBN-TinyCLR/ original build, merged with https://github.com/TekuSP/Meteostanice-CSharp/

name: Daily update dependencies

on: 
  schedule:
  # At 00:00 UTC every day.
  - cron:  '0 0 * * *'
  repository_dispatch:
    types: update-dependencies
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  dependencies-update:
    name: Update .NET nanoFramework dependencies
    timeout-minutes: 15
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install NuGet client
        uses: nuget/setup-nuget@v2.0.1
        with:
          nuget-version: 'latest'
          
      - name: Set branch environment variable
        run: |
          $tagName = "${{ github.ref_name }}"
          if (([string]::IsNullOrEmpty($tagName)))
          {
             $tagName = "master"
          }
          echo "targetBranch=$tagName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh # Explicitly use PowerShell Core (default on windows-latest for 'run')

      - uses: nanoframework/nanodu@v1.0.26
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_AUTH: ${{ secrets.PR_SECRET }}
        with:
          previewPackages: false
          solutionsToCheck: 'OpenHalo.sln'
          nugetConfig: 'nuget.config'
          gitHubAuth: '${{ env.GITHUB_AUTH }}'
          branchToPr: '${{ env.targetBranch }}'
