# Copyright (c) .NET Foundation and Contributors
# https://github.com/networkfusion/MBN-TinyCLR/ original build
name: Daily update dependencies

on: 
  schedule:
  # At 00:00 UTC every day.
  - cron:  '0 0 * * *'
  repository_dispatch:
    types: update-dependencies

defaults:
  run:
    shell: pwsh

jobs:
  dependencies-update:
    name: Update .NET nanoFramework dependencies
    timeout-minutes: 15
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: nanoframework/nf-tools
          path: tools
      - name: Install NuGet client
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - name: Update dependencies
        run: ./github-actions/update-nf-dependencies.ps1 prerelease
        working-directory: tools
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: env.CREATE_PR == 'true'
        with:
          title: '${{ env.PR_TITLE }}'
          body: |
            :warning: Automated dependency update. :warning:
            ${{ env.PR_MESSAGE }}
          committer: 'dependabot <noreply@github.com>'
          branch: ${{ env.BRANCH_NAME }}
          path: main
          labels: |
            Type: dependencies
